backend:
  name: git-gateway
  branch: main
  login: true

media_folder: "images"
public_folder: "/images"

collections:
  - name: "sobre"
    label: "Sobre"
    files:
      - file: "content/sobre/sobre.json"
        label: "Conteúdo Sobre"
        name: "sobre"
        format: "json"
        fields:
          - label: "Mídia"
            name: "media"
            widget: "object"
            fields:
              - label: "Tipo"
                name: "type"
                widget: "select"
                options: ["image", "embed"]
                hint: "Para colocar uma imagem/foto, use o seletor de 'image'. Para colocar um vídeo, use o seletor 'embed'."
              - label: "Fonte da Mídia (imagem ou vídeo)"
                name: "src"
                widget: "string"
                required: true
                hint: "Para imagens/fotos é necessário voltar a tela anterior e clicar em 'media' no menu superior, fazer o upload da imagem - selecionar a imagem - clicar em Copy path. Cole o caminho no campo. Para tipo 'video/embed', cole a URL do vídeo."
                media_library: true
              - label: "Legenda da Mídia"
                name: "description"
                widget: "string"
                required: false
                hint: "Você pode colocar uma legenda para sua foto ou vídeo."

          - name: "title"
            label: "Título"
            widget: "string"

          - name: "description"
            label: "Descrição principal"
            widget: "text"

          - name: "contatos"
            label: "Contatos"
            widget: "object"
            fields:
              - name: "email"
                label: "Email"
                widget: "string"
              - name: "linkedin"
                label: "LinkedIn"
                widget: "string"
              - name: "celular"
                label: "Celular"
                widget: "string"

          - name: "experiencia"
            label: "Experiência"
            widget: "list"
            summary: "{{fields.item}}"
            field:
              label: "Empresa"
              name: "item"
              widget: "string"

          - name: "formacao"
            label: "Formação"
            widget: "list"
            summary: "{{fields.item}}"
            field:
              label: "Curso ou Instituição"
              name: "item"
              widget: "string"

          - name: "premios"
            label: "Prêmios"
            widget: "list"
            fields:
              - name: "titulo"
                label: "Nome da Premiação"
                widget: "string"
              - name: "itens"
                label: "Conquistas"
                widget: "list"
                field:
                  name: "premio"
                  label: "Prêmio"
                  widget: "string"

  - name: "projetos"
    label: "Projetos"
    label_singular: "Projeto"
    folder: "content/projetos"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    fields:
      - name: "titulo"
        label: "Título"
        widget: "string"
      - name: "subtitulo"
        label: "Subtítulo"
        widget: "string"
        required: false
      - name: "slug"
        label: "Slug"
        widget: "string"
      - name: "thumb"
        label: "Thumbnail"
        widget: "image"
      - name: "descricao"
        label: "Descrição"
        widget: "text"
        required: false
      - label: "Conteúdo"
        name: "conteudo"
        widget: "list"
        fields:
          - name: "tipo"
            label: "Tipo"
            widget: "select"
            options: ["video", "imagem", "texto", "poster", "galeria"]
          - name: "src"
            label: "Src (para vídeo/imagem)"
            widget: "string"
            required: false
          - name: "valor"
            label: "Texto explicativo"
            widget: "text"
            required: false
          - name: "imagens"
            label: "Lista de imagens"
            widget: "list"
            field:
              label: "Imagem"
              name: "image"
              widget: "image"
            required: false
          - name: "tamanho"
            label: "Tamanho da imagem (opcional)"
            widget: "select"
            options: ["normal", "pequena"]
            required: false
            hint: "Use 'pequena' se quiser que a imagem seja exibida com largura menor."
