backend:
  name: git-gateway
  repo: iriscacais/pasta-brodo
  branch: main
  identity_url: https://auth.decapbridge.com/sites/5426f22a-43f6-4e3f-8308-23450b1bf1cb
  gateway_url: https://gateway.decapbridge.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "sobre"
    label: "Sobre"
    files:
      - file: "content/sobre/sobre.json"
        label: "Conteúdo Sobre"
        name: "sobre"
        format: "json"
        fields:
          - label: "Mídia"
            name: "media"
            widget: "object"
            fields:
              - label: "Tipo"
                name: "type"
                widget: "select"
                options: ["image", "embed"]
                hint: "Para colocar uma imagem/foto, use o seletor de 'image'. Para colocar um vídeo, use o seletor 'embed'."
              - label: "Fonte da Mídia (imagem ou vídeo)"
                name: "src"
                widget: "string"
                required: true
                hint: "Para imagens/fotos é necessário voltar a tela anterior e clicar em 'media' no menu superior, fazer o upload da imagem - selecionar a imagem - clicar em Copy path. Cole o caminho no campo. Para tipo 'video/embed', cole a URL do vídeo."
                media_library: true
              - label: "Legenda da Mídia"
                name: "description"
                widget: "string"
                required: false
                hint: "Você pode colocar uma legenda para sua foto ou vídeo."

          - name: "title"
            label: "Título"
            widget: "string"

          - name: "description"
            label: "Descrição principal"
            widget: "text"

          - name: "contatos"
            label: "Contatos"
            widget: "object"
            fields:
              - name: "email"
                label: "Email"
                widget: "string"
              - name: "linkedin"
                label: "LinkedIn"
                widget: "string"
              - name: "celular"
                label: "Celular"
                widget: "string"

          - name: "experiencia"
            label: "Experiência"
            widget: "list"
            summary: "{{fields.item}}"
            field:
              label: "Empresa"
              name: "item"
              widget: "string"

          - name: "formacao"
            label: "Formação"
            widget: "list"
            summary: "{{fields.item}}"
            field:
              label: "Curso ou Instituição"
              name: "item"
              widget: "string"

          - name: "premios"
            label: "Prêmios"
            widget: "list"
            fields:
              - name: "titulo"
                label: "Nome da Premiação"
                widget: "string"
              - name: "itens"
                label: "Conquistas"
                widget: "list"
                field:
                  name: "premio"
                  label: "Prêmio"
                  widget: "string"

  - name: "projetos"
    label: "Projetos"
    label_singular: "Projeto"
    folder: "content/projetos"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    summary: "{{fields.ordem}} - {{fields.titulo}} - {{fields.ativo | ternary('(visível)', '(oculto)')}}"
    fields:
      - name: "titulo"
        label: "Título"
        widget: "markdown"
      - name: "titulo_tamanho"
        label: "Tamanho do título"
        widget: "select"
        options:
          - { label: "Pequeno", value: "pequena" }
          - { label: "Médio (padrão)", value: "media" }
          - { label: "Grande", value: "grande" }
        default: "media"
      - name: "subtitulo"
        label: "Subtítulo"
        widget: "markdown"
        required: false
      - name: "subtitulo-tamanho"
        label: "Tamanho do Subtítulo"
        widget: "select"
        options:
          - { label: "Pequeno", value: "pequena" }
          - { label: "Médio (padrão)", value: "media" }
          - { label: "Grande", value: "grande" }
        default: "media"
      - name: "descricao"
        label: "Descrição"
        widget: "markdown"
        required: false
        hint: "Texto descritivo sobre o projeto - aparece ao lado do título e subtítulo."
      - name: "descricao_tamanho"
        label: "Tamanho da Descrição"
        widget: "select"
        options:
          - { label: "Pequeno", value: "pequena" }
          - { label: "Médio (padrão)", value: "media" }
          - { label: "Grande", value: "grande" }
        default: "media"
      - name: "ativo"
        label: "Projeto visível no site."
        widget: "boolean"
        default: true
        hint: "Marque se quiser que o projeto fique visível no site, desmarque para ocultar."
      - name: "ordem"
        label: "Ordem de exibição"
        widget: "number"
        default: 0
        hint: "Projetos com número menor aparecem antes."
      - name: "slug"
        label: "Slug"
        widget: "string"
        hint: "slug é o nome que vai aparecer na url quando o projeto for adicionado, preencha algo simples ex. skip-sem-ad."
      - name: "thumb"
        label: "Thumbnail"
        widget: "image"
        hint: "Imagem de capa."
      - label: "Conteúdo"
        name: "conteudo"
        widget: "list"
        types:
          - label: "Vídeo"
            name: "video"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "video" }
              - { name: "src", label: "URL do vídeo", widget: "string", hint: "Cole o link do YouTube ou Vimeo" }

          - label: "Imagem"
            name: "imagem"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "imagem" }
              - { name: "src", label: "Imagem", widget: "image" }
              - { name: "tamanho", label: "Tamanho", widget: "select", options: ["normal", "pequena"], required: false, hint: "Use 'pequena' se quiser que a imagem seja exibida menor." }

          - label: "Texto"
            name: "texto"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "texto" }
              - { name: "valor", label: "Texto explicativo", widget: "markdown" }
          - name: "tamanho"
            label: "Tamanho do Texto"
            widget: "select"
            options:
              - { label: "Pequeno", value: "pequena" }
              - { label: "Médio (padrão)", value: "media" }
              - { label: "Grande", value: "grande" }
            default: "media"
          - label: "Poster"
            name: "poster"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "poster" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                field: { name: "image", label: "Imagem", widget: "image" }

          - label: "Galeria"
            name: "galeria"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                field: { name: "image", label: "Imagem", widget: "image" }
          - label: "Galeria de Vídeos Horizontais"
            name: "galeria-video-horizontal"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria-video-horizontal" }
              - name: "videos"
                label: "Vídeos"
                widget: "list"
                field: { label: "URL do vídeo", name: "src", widget: "string" }
          - label: "Galeria Assimétrica"
            name: "galeria-bloco"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria-bloco" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                min: 3
                max: 3
                field: { name: "image", label: "Imagem", widget: "image" }



