backend:
  name: git-gateway
  repo: iriscacais/pasta-brodo
  branch: main
  identity_url: https://auth.decapbridge.com/sites/5426f22a-43f6-4e3f-8308-23450b1bf1cb
  gateway_url: https://gateway.decapbridge.com
  
logo_url: /images/brodo.png
editor:
  preview: false

media_folder: "images"
public_folder: "/images"

collections:
  - name: "instrucoes"
    label: "Instruções"
    delete: false
    editor:
      preview: false
      disable: true
    files:
      - file: "content/ajuda/instrucoes.json"
        label: "Como usar o CMS"
        name: "instrucoes"
        format: "json"
        delete: false
        fields:
          - label: "Texto explicativo"
            name: "texto"
            widget: "markdown"
            default: |
              ## Bem-vindo ao painel de edição do site!

              Na parte inicial do seu projeto você pode:
              - Editar a sessão **Sobre**
              - Adicionar ou editar projetos

              ### IMPORTANTE SOBRE PROJETOS:
              - Para editar um projeto, basta **clicar no card correspondente**.
              - Para adicionar um novo projeto, clique em **“New Project”** no canto superior direito.
              - **A ordem dos cards não representa a ordem em que aparecem no site.**
              - Cada card mostra:
                - Um número (campo “ordem”): **quanto maior o número, mais acima no site ele aparece**
                - Um status de visibilidade: `visível` ou `oculto`

              ### Sobre o botão **Media** (menu lateral):
              - Aqui ficam **todas as imagens** do site, inclusive imagens de menu, ícones e projetos.
              - Você pode **excluir, fazer upload ou download** de imagens.
              - **Atenção:** imagens essenciais como o menu hambúrguer ou ícones de contato **não devem ser excluídas**.
              - Caso deseje trocar um ícone, **use o mesmo nome do arquivo** para substituí-lo corretamente.

              ---
              Para instruções específicas de cada campo, acesse as abas “Sobre” ou “Projetos”, cada campo tem uma breve explicação.  

  - name: "sobre"
    label: "Sobre"
    files:
      - file: "content/sobre/sobre.json"
        label: "Conteúdo Sobre"
        name: "sobre"
        format: "json"
        fields:
          - label: "Mídia"
            name: "media"
            widget: "list"
            max: 1
            min: 1
            summary: "{{fields.tipo}}"
            hint: "Você pode escolher uma foto ou um vídeo..."
            types:
              - label: "Imagem"
                name: "imagem"
                widget: "object"
                fields:
                  - { name: "tipo", widget: "hidden", default: "imagem" }
                  - { name: "src", label: "Imagem", widget: "image", hint: "Selecione uma imagem" }
                  - { name: "description", label: "Legenda da Mídia (opcional)", widget: "string", required: false }
              - label: "Vídeo"
                name: "video"
                widget: "object"
                fields:
                  - { name: "tipo", widget: "hidden", default: "video" }
                  - { name: "src", label: "URL do vídeo", widget: "string", hint: "Cole a URL do vídeo (YouTube, Vimeo etc.)" }
                  - { name: "description", label: "Legenda da Mídia (opcional)", widget: "string", required: false }

          - name: "title"
            label: "Título"
            widget: "string"
            hint: "O texto de maior destaque da sessão sobre do site!"

          - name: "description"
            label: "Descrição principal"
            widget: "markdown"
            buttons: [bold, italic, heading-two, heading-three, quote, bulleted-list, numbered-list, link]
            editor_components: []
            hint: "Aqui você pode contar mais sobre você..."

          - name: "contatos"
            label: "Contatos"
            widget: "object"
            hint: "Se precisar editar suas informações de contato..."
            fields:
              - { name: "email", label: "Email", widget: "string" }
              - { name: "linkedin", label: "LinkedIn", widget: "string" }
              - { name: "celular", label: "Celular", widget: "string" }

          - name: "experiencia"
            label: "Experiência"
            widget: "list"
            summary: "{{fields.item}}"
            hint: "Sessão para adicionar ou atualizar o que aparece em ‘Por onde passei’..."
            field:
              label: "Empresa"
              name: "item"
              widget: "string"

          - name: "formacao"
            label: "Formação"
            widget: "list"
            summary: "{{fields.item}}"
            hint: "Sessão para adicionar ou atualizar o que aparece em ‘Formação’..."
            field:
              label: "Curso ou Instituição"
              name: "item"
              widget: "string"

          - name: "premios"
            label: "Prêmios"
            widget: "list"
            hint: "Sessão para adicionar ou atualizar Prêmios..."
            fields:
              - { name: "titulo", label: "Nome da Premiação", widget: "string" }
              - name: "itens"
                label: "Conquistas"
                widget: "list"
                field: { name: "premio", label: "Prêmio", widget: "string" }

  - name: "projetos"
    label: "Projetos"
    label_singular: "Projeto"
    folder: "content/projetos"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    summary: "{{fields.ordem}} - {{fields.titulo}} - {{fields.ativo | ternary('(visível)', '(oculto)')}}"
    fields:
      - { name: "titulo", label: "Título", widget: "string", hint: "Título do seu projeto." }
      - { name: "subtitulo", label: "Subtítulo", widget: "string", required: false, hint: "Subtítulo (opcional)..." }
      - { name: "descricao", label: "Descrição", widget: "string", required: false, hint: "Texto descritivo..." }
      - { name: "ativo", label: "Projeto visível no site.", widget: "boolean", default: true, hint: "Marque se quiser que..." }
      - { name: "ordem", label: "Ordem de exibição", widget: "number", default: 0, hint: "Projetos com número menor..." }
      - { name: "slug", label: "Slug", widget: "string", hint: "slug é o texto que aparecerá..." }
      - { name: "thumb", label: "Thumbnail", widget: "image", hint: "Imagem de capa do projeto." }

      - label: "Conteúdo"
        name: "conteudo"
        widget: "list"
        types:
          - label: "Vídeo"
            name: "video"
            widget: "object"
            hint: "Adicionar um vídeo em formato horizontal."
            fields:
              - { name: "tipo", widget: "hidden", default: "video" }
              - { name: "src", label: "URL do vídeo", widget: "string", hint: "Cole o link do YouTube ou Vimeo" }

          - label: "Imagem"
            name: "imagem"
            widget: "object"
            hint: "Adicionar uma imagem única no site."
            fields:
              - { name: "tipo", widget: "hidden", default: "imagem" }
              - { name: "src", label: "Imagem", widget: "image" }
              - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false }
              - { name: "tamanho", label: "Tamanho", widget: "select", options: ["normal", "pequena"], required: false }

          - label: "Texto"
            name: "texto"
            widget: "object"
            hint: "Adicionar quotes, listas, links ou um texto."
            fields:
              - { name: "tipo", widget: "hidden", default: "texto" }
              - name: "valor"
                label: "Texto explicativo"
                widget: "markdown"
                buttons: [bold, italic, heading-two, heading-three, quote, bulleted-list, numbered-list, link]
                editor_components: []

          - label: "Poster"
            name: "poster"
            widget: "object"
            hint: "Você pode adicionar imagens do tipo poster aqui..."
            fields:
              - { name: "tipo", widget: "hidden", default: "poster" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                fields:
                  - { name: "image", label: "Imagem", widget: "image" }
                  - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false }

          - label: "Galeria"
            name: "galeria"
            widget: "object"
            hint: "Você pode fazer uma galeria de imagem..."
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                fields:
                  - { name: "image", label: "Imagem", widget: "image" }
                  - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false }

          - label: "Galeria de Vídeos Horizontais"
            name: "galeria-video-horizontal"
            widget: "object"
            hint: "Se você tiver vídeos horizontais e quiser que apareçam lado a lado..."
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria-video-horizontal" }
              - name: "videos"
                label: "Vídeos"
                widget: "list"
                field: { label: "URL do vídeo", name: "src", widget: "string" }

          - label: "Galeria Assimétrica"
            name: "galeria-bloco"
            widget: "object"
            hint: "Ideal para imagens com proporções diferentes..."
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria-bloco" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                min: 3
                max: 3
                fields:
                  - { name: "image", label: "Imagem", widget: "image" }
                  - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false }
