backend:
  name: git-gateway
  repo: iriscacais/pasta-brodo
  branch: main
  identity_url: https://auth.decapbridge.com/sites/5426f22a-43f6-4e3f-8308-23450b1bf1cb
  gateway_url: https://gateway.decapbridge.com
  
logo_url: /images/brodo.png
editor:
  preview: false

media_folder: "images"
public_folder: "/images"

collections:
  - name: "instrucoes"
    label: "Instruções"
    delete: false
    editor:
      preview: false
      disable: true
    files:
      - file: "content/ajuda/instrucoes.json"
        label: "Como usar o painel"
        name: "instrucoes"
        format: "json"
        delete: false
        fields:
          - label: "Texto explicativo"
            name: "texto"
            widget: "text"
            readonly: true
            
  - name: "sobre"
    label: "Sobre"
    files:
      - file: "content/sobre/sobre.json"
        label: "Conteúdo Sobre"
        name: "sobre"
        format: "json"
        fields:
          - label: "Mídia"
            name: "media"
            widget: "list"
            max: 1
            min: 1
            summary: "{{fields.tipo}}"
            hint: "Você pode escolher uma foto ou um vídeo. Caso selecione imagem você verá um link para escolher uma imagem, você pode escolher uma imagem da sua galeria Media ou fazer o upload de nova imagem. Se escolher vídeo basta colar a url no campo disponível(YouTube ou Vimeo). Opcionalmente você pode adicionar uma legenda para a sua foto/ vídeo. IMPORTANTE: você só poderá escolher uma imagem ou um vídeo."
            types:
              - label: "Imagem"
                name: "imagem"
                widget: "object"
                fields:
                  - { name: "tipo", widget: "hidden", default: "imagem" }
                  - { name: "src", label: "Imagem", widget: "image", hint: "Selecione uma imagem" }
                  - { name: "description", label: "Legenda da Mídia (opcional)", widget: "string", required: false }
              - label: "Vídeo"
                name: "video"
                widget: "object"
                fields:
                  - { name: "tipo", widget: "hidden", default: "video" }
                  - { name: "src", label: "URL do vídeo", widget: "string", hint: "Cole a URL do vídeo (YouTube, Vimeo etc.)" }
                  - { name: "description", label: "Legenda da Mídia (opcional)", widget: "string", required: false }

          - name: "title"
            label: "Título"
            widget: "string"
            hint: "O texto de maior destaque da sessão sobre do site!"

          - name: "description"
            label: "Descrição principal"
            widget: "markdown"
            buttons: [bold, italic, heading-two, heading-three, quote, bulleted-list, numbered-list, link]
            editor_components: []
            hint: "Aqui você pode contar mais sobre você. Adicionar quotes, criar listas, adicionar links ou simplesmente escrever um texto."

          - name: "contatos"
            label: "Contatos"
            widget: "object"
            hint: "Se precisar editar suas informações de contato, você pode fazer isso aqui."
            fields:
              - { name: "email", label: "Email", widget: "string" }
              - { name: "linkedin", label: "LinkedIn", widget: "string" }
              - { name: "celular", label: "Celular", widget: "string" }

          - name: "experiencia"
            label: "Experiência"
            widget: "list"
            summary: "{{fields.item}}"
            hint: "Sessão para adicionar ou atualizar o que aparece em ‘Por onde passei’ no site. Clique em 'Adicionar item' para incluir uma nova experiência. O novo campo aparece no final. Para editar um existente, clique na seta > do conteúdo. Você pode alterar a ordem de exibição arrastando o botão = e pode excluir clicando no X."
            field:
              label: "Empresa"
              name: "item"
              widget: "string"

          - name: "formacao"
            label: "Formação"
            widget: "list"
            summary: "{{fields.item}}"
            hint: "Sessão para adicionar ou atualizar o que aparece em ‘Formação’ no site. Clique em 'Adicionar item' para incluir uma nova formação. O novo campo aparece no final. Para editar um existente, clique na seta > do conteúdo. Você pode alterar a ordem de exibição arrastando o botão = e pode excluir clicando no X."
            field:
              label: "Curso ou Instituição"
              name: "item"
              widget: "string"

          - name: "premios"
            label: "Prêmios"
            widget: "list"
            hint: "Sessão para adicionar ou atualizar Prêmios. Aqui você pode adicionar novas premiações e adicionar conquistas às premiações existentes. Para adicionar uma conquista, abra o nome da premiação clicando na seta > e clique em 'Adicionar item'. Para adicionar novas premiações clique em 'Adicionar prêmios'. Você pode excluir e alterar a ordem de exibição também."
            fields:
              - { name: "titulo", label: "Nome da Premiação", widget: "string" }
              - name: "itens"
                label: "Conquistas"
                widget: "list"
                field: { name: "premio", label: "Prêmio", widget: "string" }

  - name: "projetos"
    label: "Projetos"
    label_singular: "Projeto"
    folder: "content/projetos"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "slug"
    slug: "{{slug}}"
    summary: "{{fields.ordem}} - {{fields.titulo}} - {{fields.ativo | ternary('(visível)', '(oculto)')}}"
    fields:
      - { name: "titulo", label: "Título", widget: "string", hint: "Título do seu projeto." }
      - { name: "subtitulo", label: "Subtítulo", widget: "string", required: false, hint: "Subtítulo (opcional), aparece logo abaixo do título principal." }
      - { name: "descricao", label: "Descrição", widget: "string", required: false, hint: "Texto descritivo sobre o projeto (opcional), aparece ao lado do título e subtítulo." }
      - { name: "ativo", label: "Projeto visível no site.", widget: "boolean", default: true, hint: "Marque se quiser que o projeto fique visível no site, desmarque para ocultar." }
      - { name: "ordem", label: "Ordem de exibição", widget: "number", default: 0, hint: "Projetos com número menor aparecem antes na visualização de cards do site." }
      - { name: "slug", label: "Slug", widget: "string", hint: "slug é o texto que aparecerá no final da url (ex: nome-do-projeto)" }
      - { name: "thumb", label: "Thumbnail", widget: "image", hint: "Imagem de capa do projeto." }

      - label: "Conteúdo"
        name: "conteudo"
        widget: "list"
        types:
          - label: "Vídeo"
            name: "video"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "video" }
              - { name: "src", label: "URL do vídeo", widget: "string", hint: "Adicionar um vídeo em formato horizontal. Cole o link do YouTube ou Vimeo" }

          - label: "Imagem"
            name: "imagem"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "imagem" }
              - { name: "src", label: "Imagem", widget: "image", hint: "Adicionar uma imagem única no site." }
              - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false, hint: "Texto alternativo da imagem. É exibido se a imagem não carregar e também contribui para acessibilidade e SEO." }
              - { name: "tamanho", label: "Tamanho", widget: "select", options: ["normal", "pequena"], required: false }

          - label: "Texto"
            name: "texto"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "texto" }
              - name: "valor"
                label: "Texto explicativo"
                hint: "Adicionar quotes, listas, links ou um texto."
                widget: "markdown"
                buttons: [bold, italic, heading-two, heading-three, quote, bulleted-list, numbered-list, link]
                editor_components: []

          - label: "Poster"
            name: "poster"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "poster" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                fields:
                  - { name: "image", label: "Imagem", widget: "image", hint: "Você pode adicionar imagens do tipo poster aqui. Aparecem de 2 em 2 em formato grande. Se quiser que tenham um tamanho menor você pode escolher a opção galeria no lugar de poster e adicionar mais imagens lado a lado." }
                  - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false, hint: "Texto alternativo da imagem. É exibido se a imagem não carregar e também contribui para acessibilidade e SEO." }

          - label: "Galeria"
            name: "galeria"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                fields:
                  - { name: "image", label: "Imagem", widget: "image", hint: "Você pode fazer uma galeria de imagem, quando você adiciona varias imagens elas aparecerão lado ao lado. Se você quiser que apareçam em blocos (ex. 3 em cima e 3 embaixo) adicione 2 galerias com 3 imagens em cada." }
                  - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false, hint: "Texto alternativo da imagem. É exibido se a imagem não carregar e também contribui para acessibilidade e SEO." }

          - label: "Galeria de Vídeos Horizontais"
            name: "galeria-video-horizontal"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria-video-horizontal" }
              - name: "videos"
                label: "Vídeos"
                widget: "list"
                field: { label: "URL do vídeo", name: "src", widget: "string",  hint: "Se você tiver vídeos horizontais e quiser que apareçam lado a lado você pode criar uma galeria com eles aqui." }

          - label: "Galeria Assimétrica"
            name: "galeria-bloco"
            widget: "object"
            fields:
              - { name: "tipo", widget: "hidden", default: "galeria-bloco" }
              - name: "imagens"
                label: "Imagens"
                widget: "list"
                min: 3
                max: 3
                fields:
                  - { name: "image", label: "Imagem", widget: "image",   hint: "Este tipo de galeria é ideal para imagens com proporções muito diferentes. A primeira imagem define o layout, e as demais se adaptam ao lado dela." }
                  - { name: "alt", label: "Descrição da Imagem (alt)", widget: "string", required: false, hint: "Texto alternativo da imagem. É exibido se a imagem não carregar e também contribui para acessibilidade e SEO." }
